minimumReleaseAge: 1440
packages:
  - docs
  - packages/*
  - '!packages/register-tests'
  - packages/register-tests/*
  - playgrounds/*
trustPolicy: no-downgrade
trustPolicyExclude:
  - vite
  - semver
  - rehype-pretty-code
  - ua-parser-js
  - undici-types
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.2
  vitest: 4.1.9
  vite-plus: 0.2.2
  '@vitest/coverage-v8': 4.1.9
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
  # Vocs is not compatible with the Vite+ `vite` alias yet.
  vocs>vite: ^5.0.2
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
minimumReleaseAgeExclude:
  - vocs
  - vite-plus
  - '@voidzero-dev/*'
  - oxlint
  - '@oxlint/*'
  - oxlint-tsgolint
  - '@oxlint-tsgolint/*'
  - oxfmt
  - '@oxfmt/*'
  - vitest
  - '@vitest/*'
