name: Bug Report
description: Report bugs or issues.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! The more info you provide, the more we can help you.

        If you are a [Wevm Sponsor](https://github.com/sponsors/wevm?metadata_campaign=gh_issue), your issues are prioritized.

  - type: textarea
    attributes:
      label: Describe the bug
      description: Clear and concise description of the bug. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: I am doing… What I expect is… What is actually happening…
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Link to Minimal Reproducible Example
      description: "Please provide a link that can reproduce the problem: GitHub repository for runtime issues or [TypeScript Playground](https://tsplay.dev/wjQvkW) for type issues. For most issues, you will likely get asked to provide a minimal reproducible example so why not add one now :) If a report is vague (e.g. just snippets, generic error message, screenshot, etc.) and has no reproduction, it will receive a \"Needs Reproduction\" label and be auto-closed."
      placeholder: https://tsplay.dev/wjQvkW
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps or code snippets to reproduce the behavior.
    validations:
      required: false

  - type: input
    attributes:
      label: Package Version
      description: What version of abitype are you using?
      placeholder: x.y.z (do not write `latest`)
    validations:
      required: true

  - type: input
    attributes:
      label: TypeScript Version
      description: What version of TypeScript are you using? ABIType requires `typescript@>=5.0.4`.
      placeholder: x.y.z (do not write `latest`)
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Check existing issues
      description: By submitting this issue, you checked there isn't [already an issue](https://github.com/wevm/abitype/issues) for this bug.
      options:
        - label: I checked there isn't [already an issue](https://github.com/wevm/abitype/issues) for the bug I encountered.
          required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: Anything that will give us more context about the issue you are encountering.
    validations:
      required: false

