import fs from 'node:fs/promises'

// Generates ABI parameter name lookup from common names

console.log('Generating ABI parameter name lookup.')

let content =
  'export interface AbiParameterTupleNameLookup<type> extends Record<string, [type]> {\n'
for (const name of names()) content += `  ${name}: [${name}: type]\n`
content += '}\n'

const path = './packages/abitype/src/abi.ts'
const text = await fs
  .readFile(path, 'utf8')
  .then((text) =>
    text.replace(
      /export interface AbiParameterTupleNameLookup<type>[\s\S]*$/,
      content,
    ),
  )
await fs.writeFile(path, text, 'utf8')

console.log(`Done. Added ${names().size} names.`)

function names() {
  return new Set([
    '_data',
    'a',
    'account',
    'accounts',
    'address',
    'addresses',
    'admin',
    'allowFailure',
    'allowed',
    'amount',
    'approved',
    'approver',
    'ask',
    'asset',
    'assets',
    'authority',
    'available',
    'b',
    'balance',
    'bid',
    'buffer',
    'c',
    'call',
    'callData',
    'caller',
    'calls',
    'clone',
    'coinType',
    'count',
    'currency',
    'd',
    'data',
    'deadline',
    'decimals',
    'dest',
    'divisor',
    'dns',
    'dst',
    'e',
    'endTime',
    'ens',
    'errorData',
    'f',
    'failures',
    'from',
    'funder',
    'g',
    'gateway',
    'gateways',
    'guy',
    'h',
    'hash',
    'hashes',
    'i',
    'id',
    'ids',
    'idsLength',
    'implementation',
    'index',
    'interfaceId',
    'j',
    'k',
    'key',
    'l',
    'label',
    'length',
    'limit',
    'm',
    'market',
    'memo',
    'message',
    'n',
    'name',
    'needed',
    'new',
    'next',
    'nextOwner',
    'node',
    'nonce',
    'nonceKey',
    'numerator',
    'o',
    'offerer',
    'old',
    'operator',
    'order',
    'orders',
    'owner',
    'p',
    'policyId',
    'policyType',
    'previous',
    'previousOwner',
    'price',
    'primary',
    'proposer',
    'q',
    'queries',
    'quoteToken',
    'r',
    'receiver',
    'recipient',
    'refund',
    'required',
    'resolvedName',
    'resolver',
    'responses',
    'restricted',
    'returnData',
    'reverseName',
    'reverseResolver',
    's',
    'secs',
    'selector',
    'sender',
    'shares',
    'signature',
    'signer',
    'source',
    'src',
    'startTime',
    'status',
    'success',
    'symbol',
    't',
    'target',
    'timestamp',
    'to',
    'token',
    'tokenId',
    'ttl',
    'u',
    'updater',
    'user',
    'v',
    'value',
    'values',
    'valuesLength',
    'version',
    'w',
    'wad',
    'weth',
    'x',
    'y',
    'z',
    'zone',
  ])
}
