name: Canary
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  canary:
    name: Release canary
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - run: cp .npmrc packages/abitype

      - name: Setup .npmrc file
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Set version
        run: |
          cd packages/abitype
          npm --no-git-tag-version version 0.0.0
          npm --no-git-tag-version version $(npm pkg get version | sed 's/"//g')-canary.$(date +'%Y%m%dT%H%M%S')
          pnpm bun ../../.scripts/updateVersion.ts

      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: |
          cd packages/abitype
          npm publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
