name: Lock Issue

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-inactive-days: '14'
          issue-comment: |
            This issue has been locked since it has been closed for more than 14 days.

            If you found a concrete bug or regression related to it, please open a new [bug report](https://github.com/wagmi-dev/abitype/issues/new/choose) with a reproduction against the latest ABIType version. If you have any other comments you can create a new [discussion](https://github.com/wagmi-dev/abitype/discussions).
          issue-lock-reason: ''
          process-only: 'issues'
