name: Release (canary)

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - '.github/workflows/release-canary.yml'

jobs:
  build_and_publish:
    name: Release (canary)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
        pnpm-version: [7]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: pnpm i --ignore-scripts

      - name: Build
        run: pnpm build

      - name: Set version
        run: |
          npm --no-git-tag-version version minor
          npm --no-git-tag-version version $(npm pkg get version | sed 's/"//g')-canary.$(date +'%Y%m%dT%H%M%S')

      - id: publish
        name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false
          tag: canary

      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
