name: Snapshot

on: workflow_dispatch

jobs:
  release:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
        pnpm-version: [7]
    steps:
      - uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: pnpm i --ignore-scripts

      - name: Publish to npm
        uses: seek-oss/changesets-snapshot@v0
        with:
          pre-publish: pnpm build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
